version: 2

sources:
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'BERACHAIN' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
  - name: github_actions
    database: berachain
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BERACHAIN_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BERACHAIN" }}
    tables:
      - name: testnet_receipts
      - name: testnet_blocks
      - name: testnet_transactions
      - name: testnet_traces
